services:
  - type: web
    name: edumanage-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://school-and-college-erp-manga.web.app,https://school-and-college-erp-manga.firebaseapp.com
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
